# Checking New Data

In [91]:
import os
import improve_utils as iu
import pandas as pd
from tqdm import tqdm

In [67]:
gene_list = pd.read_csv('../data/CCLE/gene_list.txt', header= None).values.astype(str).flatten().tolist()
not_in_dataset = ['SEPT6', 'SEPT5', 'FGFR1OP', 'H3F3A', 'C15orf65', 'SEPT9', 'H3F3B', 'CARS']

In [61]:
df_ge = iu.load_gene_expression_data(gene_system_identifier="Gene_Symbol")
df_cn = iu.load_copy_number_data(gene_system_identifier="Gene_Symbol")

Gene expression data: (655, 30805)
Copy number data: (655, 25331)

In [75]:
# Having same columns
ge_columns = df_ge.columns
cn_columns = df_cn.columns
common_columns = list(set(ge_columns).intersection(cn_columns))
df_ge = df_ge[common_columns]
df_cn = df_cn[common_columns]

# Having same index
ge_index = df_ge.index
cn_index = df_cn.index
common_index = list(set(ge_index).intersection(cn_index))
df_ge = df_ge.loc[common_index]
df_cn = df_cn.loc[common_index]

# Order index
df_ge = df_ge.sort_index()
df_cn = df_cn.sort_index()

df_ge

,CCDC179,ALDOB,SPATA19,RNF175,RMND5A,ADCY7,PTGDR,DDN,CD109,LINC02247,...,TRIP6,GBP4,GAS5,ZNF287,TRIM7,DNM3-IT1,CBX3,CAPN15,SLC13A1,VDR
improve_sample_id,,,,,,,,,,,,,,,,,,,,,
CC_1,0.0,0.070389,0.000000,1.189034,4.214125,3.275007,0.042644,1.157044,2.935460,0.0,...,4.888987,3.187451,9.305765,3.171527,1.565597,0.432959,7.849561,4.181898,0.0,3.221877
CC_100078,0.0,0.150560,0.000000,0.432959,4.889474,2.321928,0.000000,1.669027,0.298658,0.0,...,0.933573,0.028569,10.523758,0.111031,0.389567,0.124328,9.098743,5.102658,0.0,4.663914
CC_100095,0.0,0.042644,0.000000,0.000000,3.927896,4.218781,0.000000,0.286881,4.504620,0.0,...,6.297558,0.056584,9.173602,2.983678,2.575312,0.000000,7.369554,4.405992,0.0,1.627607
CC_100396,0.0,0.000000,0.000000,0.475085,2.733354,4.211012,0.000000,0.985500,4.796494,0.0,...,6.853247,1.084064,9.281142,1.713696,4.923149,0.000000,8.050719,4.815575,0.0,2.195348
CC_100608,0.0,0.014355,0.056584,0.014355,3.575312,1.176323,0.000000,1.321928,0.111031,0.0,...,7.248307,0.084064,9.810363,1.691534,4.895303,0.000000,8.114107,4.822220,0.0,0.042644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CC_99411,0.0,0.000000,0.000000,3.627607,4.385431,3.129283,0.000000,0.669027,4.724650,0.0,...,4.930264,0.516015,10.498051,2.307429,3.257011,0.344828,8.358607,3.980939,0.0,1.970854
CC_99414,0.0,0.028569,0.000000,0.275007,3.933573,3.783457,0.000000,0.565597,3.617063,0.0,...,6.006971,0.263034,8.130365,4.106851,3.957915,0.000000,8.371428,4.539159,0.0,3.531069
CC_99416,0.0,0.000000,0.000000,0.000000,4.187451,6.334318,0.000000,0.176323,4.356848,0.0,...,6.681309,2.220330,8.734811,2.570463,4.232661,0.000000,7.457545,4.509696,0.0,3.100978
CC_99431,0.0,0.028569,0.000000,0.516015,3.806324,3.973611,0.000000,0.333424,0.659925,0.0,...,4.786596,0.124328,8.778110,2.080658,0.298658,0.000000,7.815575,3.733354,0.0,1.718088
CC_99544,0.0,0.344828,0.933573,0.014355,4.958379,3.999098,0.000000,0.150560,0.839960,0.0,...,6.631250,2.000000,10.871520,0.028569,0.422233,0.000000,7.611246,4.996389,0.0,3.440952

In [70]:
# Gene list
gene_list = pd.read_csv('../data/CCLE/gene_list.txt', header= None).values.astype(str).flatten().tolist()
# Remove genes not in dataset
for gene in not_in_dataset:
    gene_list.remove(gene)

In [83]:
gene_exp = df_ge.iloc[0]
copy_num = df_cn.iloc[0]
df_patient = pd.concat([gene_exp, copy_num], axis=1)
df_patient = df_patient.loc[gene_list]
df_patient.columns = ['gene_expression', 'copy_number']
df_patient

          gene_expression  copy_number
EXT1             4.834408     1.363876
SOCS1            1.111031     0.710906
SS18L1           4.751678     1.432955
TERT             1.416840     1.235137
FANCD2           5.083213     0.972451
...                   ...          ...
CSF1R            0.111031     0.963232
CREBBP           3.651913     0.665853
TNFRSF14         1.104337     1.465784
SOX21            0.056584     0.728576
FANCC            3.340562     1.019847

[689 rows x 2 columns]

In [87]:
if not os.path.exists('./new_data/'):
    os.makedirs('./new_data/', exist_ok=True)

In [92]:
# check if a dir exists
df_ge.shape[0]

for i, patient in tqdm(enumerate(df_ge.index)):
    gene_exp = df_ge.iloc[i]
    copy_num = df_cn.iloc[i]
    df_patient = pd.concat([gene_exp, copy_num], axis=1)
    df_patient = df_patient.loc[gene_list]
    df_patient.columns = ['gene_expression', 'copy_number']
    df_patient.to_csv(f'./new_data/{patient}.txt', sep='\t', index=True, header=True)

655it [00:12, 54.27it/s]

In [104]:
ppi = pd.read_csv('../data/PPI/PPI_network.txt', sep='\t', header=None)

ppi_new = ppi.copy()
for gene in not_in_dataset:
    ppi_new = ppi_new[ppi_new[0] != gene]
    ppi_new = ppi_new[ppi_new[1] != gene]

ppi_new

             0       1    2
0       HOXA11  CDKN2A  301
1       HOXA11     JUN  185
2       HOXA11   ACVR1  210
3       HOXA11  DICER1  216
4       HOXA11    MNX1  231
...        ...     ...  ...
110275   CIITA   PRDM1  727
110276   CIITA   MAPK1  623
110277   CIITA   PPARG  642
110278   CIITA    AFF3  213
110279   CIITA    PAX5  485

[108804 rows x 3 columns]

In [107]:
ppi_new.to_csv('../data/PPI/PPI_network_new.txt', sep='\t', index=False, header=False)